### PR TITLE
Improve Gamora elixir dep to make a request to introspection endpoint and validate cross client identity.

### PR DESCRIPTION
**Pull request by alejandrodevs**
## Addresses issue: [#TOOL-24](https://amcoit.atlassian.net/browse/TOOL-24)

Gamora should make a request to the introspection endpoint to validate the access token. It also will continue making request to userinfo endpoint but based on a different cache period. This will allow us to validate the origin of the access token and know if it is valid for the client or not.

### CODE REVIEW

**Comment by alejandrodevs** [comment]
@javierg 

I'm using `cachex` to cache information coming from IDP. I am considering change it for `redix` in order to make it easy to configure in different nodes. Both solutions have the option to implement distributed cache but IMO redix sounds easier to implement.

**Review by javierg — COMMENTED** [review]
1 things:

Not sure if gamore should be the one handling the cache, you added the ache module here... maybe a better solution will be to add into the config a CacheModule, and have an adapter that the server implements and Gamora just use.

2.
Also, consider that most of our apps are distributed, even though Cachex handles distribution it requires previous knowledge of the node names... IMO a better solution will be to leave the cache to the server and use Nebulex instead of Cachex. Which have a more flexible implementation on distribution strategies.

https://github.com/cabol/nebulex

**Comment by alejandrodevs** [comment]
@javierg As we discussed via DM, I added an adapter behavior in order to be able to create custom adapters. Could you please take another look into the PR?

**Review by javierg — APPROVED** [review]
Great implementation of adapter pattern!

:shipit:

**Pull request merged**
